name: ssh-pipeline
on:
  push:
    branches:
      - master

env:
  DIR1: "/home/github/test/test1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: ssh pipeline 1
        uses: AbelNavarro/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
          DIR2: "/home/github/test/test2"
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          script: |
            (rm -rf /home/github/test || true)
            ls -la
            echo $WELCOME
            (mkdir -p $DIR1 || true) &&
            (mkdir -p $DIR2 || true)

      - name: ssh pipeline 2
        uses: AbelNavarro/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          script: |-
            rm -rf /home/github/test
            (mkdir test1/test || true)
            ls -la

      - name: ssh pipeline 3
        uses: AbelNavarro/ssh-pipeline@master
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          script: |-
            (mkdir test1/test || true)
            mkdir -p test/test1
            rm -rf /home/github/test
